### ISSUE TITLE
Add support for XML format

### ISSUE THREAD

**Issue by Uttamb7** [Powan55/Trivial-Trivia#3]
This feature will help the user have flexibility in the game by letting the user import and export questions with the '.xml' file type, whenever we have questions in the game the read feature will be able to read raw data and format it into readable data. The write feature will be able to convert the readable data into .xml type.

##Subtask 

- [ ] Read XML File 
- [ ] Write XML File 
- [ ] Import XML File 
- [ ] Export XML File

**Comment by Uttamb7** [comment]
Adding this issue to sprint 2 backlog
