### ISSUE TITLE
Add support for JSON format

### ISSUE THREAD

**Issue by Uttamb7** [Powan55/Trivial-Trivia#5]
This feature will help the user have flexibility in the game by letting the user import and export questions with the '.json' file type, whenever we have questions in the game the read feature will be able to read raw data and format it into readable data. The write feature will be able to convert the readable data into .json type.

##Subtask

- [ ] Read JSON File
- [ ] Write JSON File
- [ ] Import JSON File
- [ ] Export JSON File
